service: dr-activation-api # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  profile: dr-admin
  region: 'us-west-1'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-1:481636229104:table/DRActivation-*"
    - Effect: Allow
      Action:
        - route53:ListResourceRecordSets
      Resource: "arn:aws:route53:::hostedzone/*"

functions:
  jobs:
    handler: jobHandler.getJobs
    events:
      - http:
          path: jobs/{state}
          method: get
          cors: true
      - http:
          path: jobs
          method: get
          cors: true
  createJob:
    handler: jobHandler.createJob
    events:
      - http:
          path: jobs
          method: post
          cors: true
  completeJob:
    handler: jobHandler.completeJob
    events:
      - http:
          path: jobs
          method: PUT
          cors: true
  jobHistory:
    handler: jobHistoryHandler.jobHistory
    events:
      - http:
          path: jobHistory/{jobId}
          method: get
          cors: true
  createJobHistory:
    handler: jobHistoryHandler.createJobHistory
    events:
      - http:
          path: jobHistory
          method: post
          cors: true
  domainInfo:
    handler: domainInfoHandler.getDomainInfo
    events:
      - http:
          path: domainInfo
          method: get
          cors: true